version: '3'
services:
  invoice:
    build:
      context: '${BACK_END}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}' 
        - 'XDEBUG=${XDEBUG}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'INVOICE_VERSION=${INVOICE_VERSION}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_INVOICE}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${INVOICE_HOST_HTTP_PORT}:80'
volumes: {}
