FROM ghcr.io/deck-app/nginx:v8.0
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php8-openssl php8-sysvmsg php8-curl
RUN apk add --no-cache zip git wget php8-pdo php8-zip

RUN mkdir -p /app
RUN mkdir -p /var/default
RUN cd /var/default

COPY default.conf /etc/nginx/conf.d/default.conf
COPY default.conf /app/

WORKDIR /var/www
#PHP display error enable or disable
ARG PHP_VERSION
COPY php_ini/php${PHP_VERSION}.ini /etc/php8/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php8/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php8/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php8-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php8/php.ini \
;fi

RUN sed -i "s#{SERVER_ROOT}#"/var/default/demo"#g" /etc/nginx/conf.d/default.conf
RUN sed -i "s#{SERVER_ROOT}#"/var/www/public"#g" /app/default.conf

#Application Download
RUN curl -fLk -o /tmp/ninja.zip  "https://download.invoiceninja.com"
RUN mkdir /tmp/ninja-src
RUN unzip /tmp/ninja.zip -d /tmp/ninja-src

#Application2 Download
RUN curl -fLk -o /var/default/demo.zip  "https://github.com/nabad600/demo/releases/download/v1.0.0/demo.zip"
RUN unzip /var/default/demo.zip -d /var/default/

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh
CMD ["/sbin/runit-wrapper"]
ENTRYPOINT ["/docker-entrypoint.sh"]
#CMD ["/sbin/runit-wrapper"]