FROM ghcr.io/deck-app/nginx:v8.0
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php8-openssl php8-sysvmsg php8-curl
RUN apk add --no-cache zip git wget php8-pdo php8-zip rsync

COPY default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www
#PHP display error enable or disable
ARG PHP_VERSION
COPY php_ini/php${PHP_VERSION}.ini /etc/php8/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php8/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php8/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php8-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php8/php.ini \
;fi

#Application Download
RUN curl -fLk -o /tmp/ninja.zip  "https://github.com/invoiceninja/invoiceninja/releases/download/v5.3.39/invoiceninja.zip"
RUN mkdir /tmp/ninja-src
RUN unzip /tmp/ninja.zip -d /tmp/ninja-src

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh
CMD /docker-entrypoint.sh & /sbin/runit-wrapper